### ISSUE TITLE
Some Ad Hoc/Miscellaneous questions from CodeForces

### ISSUE THREAD

**Issue by M-Manas-s** [saumyasrivastava08/Important_Coding_Problems#122]
Hey! I want to add some good Ad Hoc questions from Codeforces. Please assign me to this.

**Comment by saumyasrivastava08** [comment]
> Hey! I want to add some good Ad Hoc questions from Codeforces. Please assign me to this.

Go a head .
5 questions -1PR

**Comment by M-Manas-s** [comment]
PR #136 opened. Thank You
