### ISSUE TITLE
Codechef Problems

### ISSUE THREAD

**Issue by Atharvp18** [saumyasrivastava08/Important_Coding_Problems#14]
I want to add cpp problem solutions from codechef platform.

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234

**Comment by gb07bh** [comment]
I would like to be assigned this so that I can add few more problem solutions to this.

**Comment by saumyasrivastava08** [comment]
> I would like to be assigned this so that I can add few more problem solutions to this.

Go a head!! Add different Qyestions
