### ISSUE TITLE
Codeforces problems.

### ISSUE THREAD

**Issue by MohitAswani** [saumyasrivastava08/Important_Coding_Problems#16]
I want to add CPP problem solutions from Codeforces.

**Comment by rushendra910** [comment]
I would like to add solutions to some Codeforces problems in C++. Please assign this issue to me under 'hacktoberfest2021' tag. Thank you.

**Comment by saumyasrivastava08** [comment]
> I would like to add solutions to some Codeforces problems in C++. Please assign this issue to me under 'hacktoberfest2021' tag. Thank you.

Go a head make sure to add the link of the problem and dont repeat the code.

**Comment by rushendra910** [comment]
@saumyasrivastava08 sure. Please assign the hacktoberfest2021 tag too. Thank you

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234

**Comment by droidmaximus** [comment]
can i contribute to the repo?
