### ISSUE TITLE
Add Dynamic Programming Questions 

### ISSUE THREAD

**Issue by saumyasrivastava08** [saumyasrivastava08/Important_Coding_Problems#2]
**Rules to create PR**

1.) Everyone should add Dynamic Programming Questions to only the DP section.
2.) If you are using different language create one folder inside the DP folder  name it as your language name eg:- JAVA, Python etc.
3.) If the folder of that language is already present then write your code over there.
4.) Add the test cases with input & output fields.

**Comment by astelrastogi** [comment]
Can i work on this issue?

**Comment by saumyasrivastava08** [comment]
I have assigned one issue to you after that you can work here

> Can i work on this issue?

**Comment by anand722000** [comment]
I would like to work on this... please also assign me  : )

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234

**Comment by khanjasir90** [comment]
Can i add to! since there are multiple dp standard problems

**Comment by khanjasir90** [comment]
so do i need to create another issue for adding other  dp problem

**Comment by saumyasrivastava08** [comment]
> Can i add to! since there are multiple dp standard problems

Yes Go a head . Link Your PR to the issue.
