### ISSUE TITLE
Add Description of Hacktoberfest and information about this repo.

### ISSUE THREAD

**Issue by saumyasrivastava08** [saumyasrivastava08/Important_Coding_Problems#3]
**Rules to create PR**

1.) Add this in Readme.md section .

**Comment by shubhnanda** [comment]
please assign me this issue

**Comment by saumyasrivastava08** [comment]
> please assign me this issue

You can add more things in documentation . Like Steps how tp create Pr .
Create a issue what the things you want to add in documentation. I will add the labels
