### ISSUE TITLE
Atcoder-dp-problem(queens on grid)-explanation

### ISSUE THREAD

**Issue by navjotdadwal** [saumyasrivastava08/Important_Coding_Problems#38]

**Comment by navjotdadwal** [comment]
this i want to add can you assign?

**Comment by navjotdadwal** [comment]
It is a very good E level problem

**Comment by navjotdadwal** [comment]
i can also add my cpp code to solve this

**Comment by saumyasrivastava08** [comment]
This Question is already assigned to someone .  if you want to add more Dp problem do add in DP section and add if the question is not present.
