### ISSUE TITLE
Added Codeforces Type B Problem in Java

### ISSUE THREAD

**Issue by AdrshAzd** [saumyasrivastava08/Important_Coding_Problems#4]

**Comment by aniket-24** [comment]
Please assign me this issue!

**Comment by saumyasrivastava08** [comment]
@aniket-24  You can add more questions in Codeforces/Java section . Dont repeat the question

**Comment by aniket-24** [comment]
So, do I have to create a separate issue for this? @saumyasrivastava08

**Comment by saumyasrivastava08** [comment]
> So, do I have to create a separate issue for this? @saumyasrivastava08

No you can create PR mentioning this issue. Add the link of question in the code.

**Comment by aniket-24** [comment]
Okay!
