### ISSUE TITLE
Problemset-on-Combinatorics

### ISSUE THREAD

**Issue by navjotdadwal** [saumyasrivastava08/Important_Coding_Problems#55]
Can you please assign this to me mam?

**Comment by saumyasrivastava08** [comment]
> Can you please assign this to me mam?
Create a folder then go a head.

**Comment by navjotdadwal** [comment]
Ma'am i have created PR for this topic please merge so that i can make new PR's  for other topics

**Comment by navjotdadwal** [comment]
ma'am will you merge my issues one by one or all at the same time if you tell this i can work accordingly.

**Comment by navjotdadwal** [comment]
mam can you please tell do we need to make 4 PR on 4 different repositories or making 4PR on 1 repository will also work

**Comment by navjotdadwal** [comment]
Mam please have a look on the PR for issue #53 which i have made and merge
it so that i can add further topics
