### ISSUE TITLE
T8: Data Structures: NQueens problem

### ISSUE THREAD

**Issue by NitikaGupta16** [saumyasrivastava08/Important_Coding_Problems#65]
I would like to make hacktoberfest contribution under Data Structures: T8 Recursion by adding the solution to the famous NQueens problem.

**Comment by saumyasrivastava08** [comment]
> I would like to make hacktoberfest contribution under Data Structures: T8 Recursion by adding the solution to the famous NQueens problem.

Go A head . Read The rules before Creating PR.

**Comment by saumyasrivastava08** [comment]
Already Done you can go with other problems.
