### ISSUE TITLE
Add Recursion Questions.

### ISSUE THREAD

**Issue by saumyasrivastava08** [saumyasrivastava08/Important_Coding_Problems#7]
**Rules to create PR**

1.) Everyone should add **Recursion** Questions to only the Recurssion section.
2.) If you are using different language (which is not present in folder) create one folder inside the Recurssion folder name it as your language name eg:- JAVA, Python etc.
3.) If the folder of that language is already present then write your code over there.
4.) Add the test cases with input & output fields.

**Comment by astelrastogi** [comment]
Can i work on this issue?

**Comment by isha614** [comment]
can I solve the issue?

**Comment by isha614** [comment]
Please assign me this issue!

**Comment by gb07bh** [comment]
Please assign me this issue!

**Comment by saumyasrivastava08** [comment]
As @astelrastogi asked first so the issue is assigned to her.

**Comment by saumyasrivastava08** [comment]
> Please assign me this issue!

You can Add other questions(DSA) by creating new issue. Or add the recurssion question which is not present.

**Comment by Pradumnasaraf** [comment]
> > Please assign me this issue!
> 
> You can Add other questions(DSA) by creating new issue. Or add the recurssion question which is not present.

Hope Still, it will count toward the hacktober fest.?

**Comment by Pradumnasaraf** [comment]
> > Please assign me this issue!
> 
> You can Add other questions(DSA) by creating new issue. Or add the recurssion question which is not present.

@saumyasrivastava08 Hope Still, it will count toward the hacktober fest.?

**Comment by saumyasrivastava08** [comment]
> Please assign me this issue!

You can add the questions which are not present

**Comment by Atharvp18** [comment]
Please assign me this task. I will add a recursion problem in c++.

**Comment by saumyasrivastava08** [comment]
> Please assign me this task. I will add a recursion problem in c++.

Issue is already assign . You can add other Questions in C++. Create new issue if I find it proper will add the label of **hacktoberfest**

**Comment by isha614** [comment]
> > Please assign me this issue!
> 
> You can add the questions which are not present

so will it be contributed in hacktoberfest?

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234

**Comment by saumyasrivastava08** [comment]
> > > Please assign me this issue!
> > 
> > 
> > You can add the questions which are not present
> 
> so will it be contributed in hacktoberfest?

Yes It will be & Please link the issue also to the PR which you are creating.

**Comment by astelrastogi** [comment]
Created a PR : https://github.com/saumyasrivastava08/Important_Coding_Problems/pull/69
Pls check

**Comment by deenu-1001** [comment]
can you assign this to me?

**Comment by isha614** [comment]
> > > > Please assign me this issue!
> > > 
> > > 
> > > You can add the questions which are not present
> > 
> > 
> > so will it be contributed in hacktoberfest?
> 
> Yes It will be & Please link the issue also to the PR which you are creating.

So if I add another recursion question which is not present, so can you assign to me?

**Comment by saumyasrivastava08** [comment]
> > > > > Please assign me this issue!
> > > > 
> > > > 
> > > > You can add the questions which are not present
> > > 
> > > 
> > > so will it be contributed in hacktoberfest?
> > 
> > 
> > Yes It will be & Please link the issue also to the PR which you are creating.
> 
> So if I add another recursion question which is not present, so can you assign to me?

Sure go a head . if issue is there link your PR with that
