### ISSUE TITLE
Balanced Array

### ISSUE THREAD

**Issue by ritika728** [saumyasrivastava08/Important_Coding_Problems#71]
Given an array of even size n, we need to find minimum value that can be added to an element so that array become balanced. An array is balanced if the sum of the left half of the array elements is equal to the sum of right half.

**Comment by ritika728** [comment]
@saumyasrivastava08 Please assign me this!

**Comment by moazzam07** [comment]
@saumyasrivastava08 can i also work on this?

**Comment by deenu-1001** [comment]
can you assign this to me?
