### ISSUE TITLE
Codeforces-problem-C

### ISSUE THREAD

**Issue by moazzam07** [saumyasrivastava08/Important_Coding_Problems#77]

**Comment by moazzam07** [comment]
@saumyasrivastava08 please assign me this

**Comment by saumyasrivastava08** [comment]
> @saumyasrivastava08 please assign me this

Already there issue #16 . Create your PR with issue #16 and dont repeat the question

**Comment by moazzam07** [comment]
@saumyasrivastava08 can u please assign me there?

**Comment by moazzam07** [comment]
or it is unnecessary
