### ISSUE TITLE
Add one problem in codeforces/practice C++ section

### ISSUE THREAD

**Issue by righteous09** [saumyasrivastava08/Important_Coding_Problems#78]
Hey @saumyasrivastava08 plz assign this issue to me, I would like to add one codeforces practice problem 1579/E2 name as 
E2. Array Optimization by Deque.

**Comment by saumyasrivastava08** [comment]
> Hey @saumyasrivastava08 plz assign this issue to me, I would like to add one codeforces practice problem 1579/E2 name as E2. Array Optimization by Deque.

This Question is already there .
You can add other CF questions and 5 questions will be consider as One PR.
