### ISSUE TITLE
Data Structures: T14

### ISSUE THREAD

**Issue by NitikaGupta16** [saumyasrivastava08/Important_Coding_Problems#83]
I want to contribute to Data Structures: T14. Please assign me this issue.

**Comment by droidmaximus** [comment]
I am quite good at dsa. Please assign me this issue. and also please keep this under the tag of hacktoberfest2021. Thank you

**Comment by saumyasrivastava08** [comment]
> I am quite good at dsa. Please assign me this issue. and also please keep this under the tag of hacktoberfest2021. Thank you

You can add the questions name the topic?

**Comment by saumyasrivastava08** [comment]
> I want to contribute to Data Structures: T14. Please assign me this issue.

Add the question atleast 5 which are not present there.
5que-1pr
along with testcases

**Comment by NitikaGupta16** [comment]
> > I want to contribute to Data Structures: T14. Please assign me this issue.
> 
> Add the question atleast 5 which are not present there. 5que-1pr along with testcases

Okay, sure.
