### ISSUE TITLE
Add Algorithms Used in DSA in c++.

### ISSUE THREAD

**Issue by saumyasrivastava08** [saumyasrivastava08/Important_Coding_Problems#9]
**Rules:-**
1:- Create a new folder of Algorithm(if not created already). Inside that folder create C++. (if the folders are already created skip the point)
2.:- Add new algorithm with appropriate description.
3:- Add two test case along with input and output.

**Comment by MohitAswani** [comment]
Can you provide a little more clarity on which algorithms we can add?

**Comment by anand722000** [comment]
I would like to work please assign me

**Comment by SanskritiKhatiyan** [comment]
@saumyasrivastava08 I would like to work on this plzzz assign this to me.

**Comment by saumyasrivastava08** [comment]
> Can you provide a little more clarity on which algorithms we can add?

You can add all the DSA algorithms. (any language)

**Comment by Skiena34** [comment]
I would like to work on it

**Comment by saumyasrivastava08** [comment]
> I would like to work on it

Add the Algorithms which are not present .

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
following are my accounts:
https://codeforces.com/profile/navjotdadwal
https://www.codechef.com/users/navjot1234

**Comment by deenu-1001** [comment]
can you assign this to me?

**Comment by anand722000** [comment]
i would like to add my own created sorting algorithm ...
