### ISSUE TITLE
Balancing Parenthesis problem using cpp

### ISSUE THREAD

**Issue by theparasgami** [saumyasrivastava08/Important_Coding_Problems#94]
Hey,
I would like to add the code of the Balancing Parenthesis problem using CPP with the stack.
Requesting to be assigned to this issue under the 'hacktoberfest2021' label. Thanks.

**Comment by AB-Jeet** [comment]
Pls assign it to me .

**Comment by AB-Jeet** [comment]
Pls assign it to me.

**Comment by saumyasrivastava08** [comment]
> Hey, I would like to add the code of the Balancing Parenthesis problem using CPP with the stack. Requesting to be assigned to this issue under the 'hacktoberfest2021' label. Thanks.

already there
